import os

# Get data file path
path = os.getcwd()
data_path = path + '/data/'

# Files which are generated by the NN
flist_model = ['tf.log', 'checkpoint', 'model.ckpt.data-00000-of-00001', 'model.ckpt.index', 'model.ckpt.meta']

# Processed test and train files
flist_presets = ['test_set_vec.csv', 'train_set.csv', 'train_set_shuffled.csv', 'train-data-reduced.csv',
                 'lexicon.pickle']


def cleaner(flist):
    for file in flist:
        fname = data_path + file
        if os.path.isfile(fname):
            os.remove(fname)


def clean_model():
    cleaner(flist_model)


def clean_presets():
    cleaner(flist_presets)
